spring.application.name=jobflow

spring.datasource.url= jdbc:postgresql://localhost:5432/jobflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Variables d'environnements
jwt.secret = ${JWT_SECRET:ma_super_cle_secrete_tres_longue_pour_jobflow_2026_qui_fait_plus_de_32_caracteres}
jwt.expiration = ${JWT_EXPIRATION:86400000}


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
